version: "3.9"

services:
  node:
    image: node:18-alpine
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - ./front:/app
    working_dir: /app
    command: npm run dev

  python:
    image: python:3.10-alpine
    environment:
      TOKEN_HUGGINGFACE
    networks:
      - backend
    volumes:
      - ./back:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"

networks:
  backend:
    driver: bridge
